In [28]:
import torch
import numpy as np
import time

In [1]:
with open("book.txt","r",encoding="utf-8") as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
print(len(chars))

['\n', ' ', '"', '#', '&', '(', ')', '*', ',', '-', '.', '0', '1', '2', '4', '5', '6', '7', '8', '9', ':', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'W', 'Y', '[', ']', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y']
68


In [ ]:
str_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_str = {i:ch for i,ch in enumerate(chars)}

3

In [ ]:
# 定义两个方法，将一个列表中的所有字母/数字都转化成数字/字母
encode = lambda s: [str_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_str[i] for i in l]) # 按照分隔符""将字符连接起来
decode2 = lambda l: [int_to_str[i] for i in l]
en_data = encode("hello")
en_data
de_data = decode(en_data)
de_data

'hello'

In [22]:
test1 = encode("hello")
print(test1)
test2 = decode(test1)
print(test2)
test3 =decode2(test1)
print(test3)

[52, 49, 56, 56, 59]
hello
['h', 'e', 'l', 'l', 'o']


In [15]:
data = torch.tensor(
    encode(chars),
    dtype = torch.long
)
data[:100]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67])

In [24]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-47,  36, -56,  -4, -54,  84])

In [ ]:
# 不进行初始化，张量的内容是随机的
a = torch.empty((2,3),dtype=torch.int64)
print(a)
empty_like = torch.empty_like(a)
print(empty_like)

tensor([[7301031405359874420, 2318339484618530918, 7020669167999134762],
        [2323703971783140717, 5557490814309720430, 8245886930163559781]])
tensor([[ 94526650967056,     21474836480, 140702158767024],
        [140702036541808, 140702022330352,               0]])


In [32]:
# why using cuda(GPU) is necessary
device = "cuda" if torch.cuda.is_available else "cpu"
print(device)
mat1_G = torch.rand(10000,10000).to(device)
mat2_G = torch.rand(10000,10000).to(device)
mat1 = torch.rand(10000,10000)
mat2 = torch.rand(10000,10000)
start_time = time.time()
result_G = mat1_G @ mat2_G
end_time = time.time()
using_time_CUDA = end_time - start_time

start_time = time.time()
result_C = np.multiply(mat1, mat2)
end_time = time.time()
using_time_CPU = end_time - start_time
print("cuda using time:{:.8f}".format(using_time_CUDA))
print("CPU using time:{:.8f}".format(using_time_CPU))

print(f"cuda using time: {using_time_CUDA:.8f}")
print(f"CPU using time: {using_time_CPU:.8f}")

cuda
cuda using time:0.00044107
CPU using time:0.33471227
cuda using time: 0.00044107
CPU using time: 0.33471227
