In [2]:
import torch
import numpy as np
import time

In [1]:
with open("book.txt","r",encoding="utf-8") as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
print(len(chars))

['\n', ' ', '"', '#', '&', '(', ')', '*', ',', '-', '.', '0', '1', '2', '4', '5', '6', '7', '8', '9', ':', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'W', 'Y', '[', ']', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y']
68


In [7]:
str_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_str = {i:ch for i,ch in enumerate(chars)}

3

In [21]:
# 定义两个方法，将一个列表中的所有字母/数字都转化成数字/字母
encode = lambda s: [str_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_str[i] for i in l]) # 按照分隔符""将字符连接起来
decode2 = lambda l: [int_to_str[i] for i in l]
en_data = encode("hello")
en_data
de_data = decode(en_data)
de_data

'hello'

In [22]:
test1 = encode("hello")
print(test1)
test2 = decode(test1)
print(test2)
test3 =decode2(test1)
print(test3)

[52, 49, 56, 56, 59]
hello
['h', 'e', 'l', 'l', 'o']


In [15]:
data = torch.tensor(
    encode(chars),
    dtype = torch.long
)
data[:100]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67])

In [24]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-47,  36, -56,  -4, -54,  84])

In [25]:
# 不进行初始化，张量的内容是随机的
a = torch.empty((2,3),dtype=torch.int64)
print(a)
empty_like = torch.empty_like(a)
print(empty_like)

tensor([[7301031405359874420, 2318339484618530918, 7020669167999134762],
        [2323703971783140717, 5557490814309720430, 8245886930163559781]])
tensor([[ 94526650967056,     21474836480, 140702158767024],
        [140702036541808, 140702022330352,               0]])


In [32]:
# why using cuda(GPU) is necessary
device = "cuda" if torch.cuda.is_available else "cpu"
print(device)
mat1_G = torch.rand(10000,10000).to(device)
mat2_G = torch.rand(10000,10000).to(device)
mat1 = torch.rand(10000,10000)
mat2 = torch.rand(10000,10000)
start_time = time.time()
result_G = mat1_G @ mat2_G
end_time = time.time()
using_time_CUDA = end_time - start_time

start_time = time.time()
result_C = np.multiply(mat1, mat2)
end_time = time.time()
using_time_CPU = end_time - start_time
print("cuda using time:{:.8f}".format(using_time_CUDA))
print("CPU using time:{:.8f}".format(using_time_CPU))

print(f"cuda using time: {using_time_CUDA:.8f}")
print(f"CPU using time: {using_time_CPU:.8f}")

cuda
cuda using time:0.00044107
CPU using time:0.33471227
cuda using time: 0.00044107
CPU using time: 0.33471227


In [34]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, num_samples = 6, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 0, 1])


In [37]:
a = torch.tensor([1,2,3,4])
out = torch.cat((a, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [45]:
out = torch.zeros(5,5).masked_fill(
    torch.tril(torch.ones(5,5)) == 0,
    float('-inf')
)
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [46]:
# 输出每个数的指数
out_e = torch.exp(out)
out_e

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

torch.transpose():交换特定的维度
torch.reshape(): 重塑张量的形状

In [51]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
print(out.shape)
input_2 = torch.zeros(2,3)
input_3 = torch.reshape(input_2,(1,6))
print(input_3.shape)

torch.Size([4, 3, 2])
torch.Size([1, 6])


堆叠

In [53]:
tensor1 = torch.Tensor([1,2,3])
tensor2 = torch.Tensor([4,5,6])
tensor3 = torch.Tensor([7,8,9])
tensor_stack = torch.stack([tensor1, tensor2, tensor3])
print(tensor1.shape)
print(tensor_stack.shape)

torch.Size([3])
torch.Size([3, 3])


In [59]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3,8,bias = False)
output = linear(sample)
output.shape

torch.Size([8])

In [61]:
import torch.nn.functional as F
sample = torch.tensor([1.0, 2.0, 3.0])
softmax_output = F.softmax(sample,dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

nn.embedding()

In [64]:
vocab_size = 100
embedding_dim = 8
embedding = nn.Embedding(vocab_size, embedding_dim)
input_indices = torch.LongTensor([1,4,32,6])
embedded_output = embedding(input_indices)
embedded_output.shape

torch.Size([4, 8])

In [67]:
a = torch.tensor(
    [
        [1,2],[3,4],[5,6]
    ]
)
b = torch.tensor(
    [
        [7,8,9],[10,11,12]
    ]
)
print(a.shape)
print(b.shape)
c = a @ b # equal to torch.matmul
d = torch.matmul(a,b)
print(c.shape)
print(c == d)

torch.Size([3, 2])
torch.Size([2, 3])
torch.Size([3, 3])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [14]:
i_64 = torch.randint(0,10,(3,2))
f_32 = torch.rand(3,2)
print(f_32.dtype)
f_64 = i_64.float()
print(f_64.dtype)

torch.float32
torch.float32
